-- Type Bound Supabase schema
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Anonymous typist' check (char_length(username) between 2 and 24 and username ~ '^[[:alnum:]_ -]+$'),
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('easy','medium','hard','hardcore','speed','custom','drill','daily')),
  score integer not null default 0 check (score between 0 and 1000000000),
  letters_per_second numeric(7,2) not null default 0 check (letters_per_second between 0 and 1000),
  accuracy numeric(5,2) not null default 0 check (accuracy >= 0 and accuracy <= 100),
  duration numeric(7,2) not null default 0 check (duration between 0 and 3600),
  challenge_date date,
  created_at timestamptz not null default now()
);

create index if not exists runs_mode_score_idx
  on public.runs (mode, score desc, created_at desc);

create index if not exists runs_mode_speed_idx
  on public.runs (mode, letters_per_second desc, created_at desc);

create index if not exists runs_user_created_idx
  on public.runs (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.runs enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
create policy "Profiles are publicly readable"
  on public.profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can read their own runs" on public.runs;
create policy "Users can read their own runs"
  on public.runs for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Anyone can read leaderboard runs" on public.runs;
create policy "Anyone can read leaderboard runs"
  on public.runs for select
  to anon, authenticated
  using (true);

drop policy if exists "Users can insert their own runs" on public.runs;
create policy "Users can insert their own runs"
  on public.runs for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users may not edit or delete submitted scores from the browser.
drop policy if exists "Users cannot update runs" on public.runs;
drop policy if exists "Users cannot delete runs" on public.runs;

-- Automatically create a profile row when a new Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, case
    when coalesce(new.raw_user_meta_data ->> 'username', '') ~ '^[[:alnum:]_ -]{2,24}$'
      then coalesce(new.raw_user_meta_data ->> 'username', 'Anonymous typist')
    else 'Anonymous typist'
  end)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Public leaderboard query. Speed Only and Custom Text should sort by l/s
-- in application code or through a separate mode-specific query.
create or replace view public.leaderboard_runs
with (security_invoker = true)
as
select
  runs.id,
  runs.mode,
  runs.score,
  runs.letters_per_second,
  runs.accuracy,
  runs.duration,
  runs.challenge_date,
  runs.created_at,
  profiles.username,
  profiles.avatar_path
from public.runs
left join public.profiles on profiles.id = runs.user_id;
